# Generated by Django 4.2.10 on 2026-04-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='zona',
            field=models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], default='Urbano', max_length=10),
        ),
    ]
