# Generated by Django 4.2.10 on 2026-04-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_inmuebles_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmuebles',
            options={},
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='tipo_negocio',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='ubicacion_especifica',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='zona',
        ),
        migrations.AlterModelTable(
            name='inmuebles',
            table=None,
        ),
    ]
