# Generated by Django 4.2.10 on 2026-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_alter_inmuebles_options_remove_inmuebles_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmuebles',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='tipo_negocio',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], default='Venta', max_length=20),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='valor_inmueble',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='zona',
            field=models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='inmuebles',
            table='propiedades_inmuebles',
        ),
    ]
