# Generated by Django 4.2.10 on 2026-04-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_inmuebles_options_inmuebles_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
