# Generated by Django 4.2.10 on 2026-05-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_inmuebles_ubicacion_especifica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
