# Generated by Django 4.2.10 on 2026-05-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_usuarios_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='propietario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.usuarios', verbose_name='Propietario'),
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to='propiedades.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Historial de búsquedas',
                'db_table': 'historial_busquedas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='propiedades.inmuebles')),
                ('usuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='propiedades.usuarios')),
            ],
            options={
                'db_table': 'favoritos',
                'managed': True,
                'unique_together': {('usuario', 'inmueble')},
            },
        ),
    ]
