# Generated by Django 4.2.10 on 2026-05-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_inmuebles_propietario_historialbusqueda_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('negociacion', 'En Negociación'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_asesor', to='propiedades.usuarios')),
                ('cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_cliente', to='propiedades.usuarios')),
                ('inmueble', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='propiedades.inmuebles')),
            ],
            options={
                'db_table': 'conversaciones',
                'ordering': ['-actualizado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/')),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='propiedades.conversacion')),
                ('remitente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='propiedades.usuarios')),
            ],
            options={
                'db_table': 'mensajes',
                'ordering': ['creado'],
                'managed': True,
            },
        ),
    ]
